type: rpm-ostree
repos:
  - https://copr.fedorainfracloud.org/coprs/wezfurlong/wezterm-nightly/repo/fedora-%OS_VERSION%/wezfurlong-wezterm-nightly-fedora-%OS_VERSION%.repo
  - https://repository.mullvad.net/rpm/stable/mullvad.repo
install:
  # for brew
  - gcc
  - make
  - mesa-libGLU
  - podman-compose
  - podman-plugins
  - podman-tui
  - podmansh
  # hyprland packages
  - hyprland
  - xdg-desktop-portal-hyprland
  - waybar
  - xorg-x11-server-Xwayland
  - xdg-user-dirs
  - wezterm
  # sway pkg
  - sway
  # android
  - android-tools
  - android-file-transfer
  # common utils
  - swaybg
  - swayidle
  - swaylock
  - tuned
  - tuned-utils
  - tuned-switcher
  - polkit-gnome
  - libseat
  - network-manager-applet
  - system-config-printer
  - firewall-config
  - blueman
  - thunar
  - thunar-archive-plugin
  - imv
  - kvantum
  - eza
  - gnome-disk-utility
  - mako
  - xarchiver
  - pavucontrol
  - swappy
  - docker-compose
  # qt shiz
  - sddm
  - qt5ct
  - qt6ct
  - qt6-qtwayland
  - qt5-qtwayland
  - qt5-qtgraphicaleffects
  - qt5-qtquickcontrols2
  - qt5-qtsvg
  # launchers
  - fuzzel
  # terminals
  - foot
  # screenshotting
  - grimshot
  - wdisplays
  - gnome-keyring
  # fonts
  - overpass-fonts
  - overpass-mono-fonts
  - google-noto-emoji-fonts
  - google-noto-fonts-common
  - google-roboto-fonts
  - google-noto-sans-fonts
  # config deps
  - light
  - fish
  - wtype
  # audio
  - pipewire
  - wireplumber
  - pipewire-alsa
  - pipewire-jack-audio-connection-kit
  - pipewire-pulseaudio
  # git askpass
  - ksshaskpass
  # Mullvad
  - mullvad-vpn
remove:
  - firefox # default firefox removed in favor of flatpak
  - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
  - toolbox
optfix:
  - Mullvad VPN
