name: uhypr
description: custom sway image for framework laptop.

base-image: quay.io/fedora-ostree-desktops/sway-atomic
image-version: 43

modules:
  - type: files
    files:
      - source: usr
        destination: /usr
      - source: etc
        destination: /etc

  - type: script
    scripts:
      - vscode.sh
  - from-file: module_config/packages.yml

  - from-file: module_config/systemd.yml
  - type: signing

  # dotfile stuff
  - type: brew
    nofile-limits: true # increase nofile limits
    brew-analytics: false # disable telemetry

  - type: chezmoi
    repository: "https://github.com/gerblesh/dotfiles" # my dotfiles repo
    all-users: true # make users have to enable chezmoi manually
    file-conflict-policy: replace # override changed files with those from the repo
    disable-update: true
    disable-init: false

