# image will be published to ghcr.io/<user>/<name>
name: uhypr
# description will be included in the image's metadata
description: custom sway image for framework laptop

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: common.yml
  - type: files
    files:
      - framework/foot: /usr/etc/xdg/foot
      - framework/fuzzel: /usr/etc/xdg/fuzzel
      - framework/sway: /usr/etc/sway
      - framework/mako: /usr/etc/homedir/.config/mako
      - framework/sddm: /usr/share/sddm
